language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y ttf-ubuntu-font-family
  - npm cache verify
  - npm cache clean --force
  - npm install -g npm@latest
script:
  - npm run analyze
  - npm run createCVHTML
  - npm run createCVPDF
  - sleep 20
  - ls out
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    all_branches: false
